### PR TITLE
travis.yml for qabel-drop

### LINKED ISSUE #18: Build the meta repository
If we change the drop server, qabel-core could be broken.
I think, we should also test all the other repositories. What do you think?

### PR DESCRIPTION
**Pull request by NanNor**
travis.yml for qabel-drop. I will commit and force push it like in Qabel/qabel-storage#23
closes #18

### CODE REVIEW

**Comment by thechauffeur** [comment]
@NanNor the result looks good. Please rebase your 4 commits into just 1 commit and force push again before I merge this.

And a small hint: We have more than one repository and each repository counts the issue and pull request numbers on it's own. That means if you write `#23` in this repository GitHub references the issue / pull request number 23 in this repository. If you want to reference issues / pull request from another repository - let's call it `qabel-example-repo` - you have to write `Qabel/qabel-example-repo#23`.

**Comment by NanNor** [comment]
Is it right now? And thanks for the advice

**Comment by thechauffeur** [comment]
> Is it right now? And thanks for the advice

Do not tell that this is a squashed commit. Just write the whole commit message like you only did this one commit.

**Comment by thechauffeur** [comment]
And edit the description of this PR to change `#23`

**Comment by jasinai** [comment]
Please change the commit message.
This does **not** test the other repositories like qabel-core(qabel-storage has no tests so far)
Change line 20 to:
```
script:
 - nosetests
 - ./gradlew check
```

**Comment by thechauffeur** [comment]
@NanNor please rebase the history. Talk to @cburkert about how to do this.

**Comment by cburkert** [comment]
Repase done, neat and clean now.

**Comment by jasinai** [comment]
Looks good now.
Gradle is a little bit verbose in this repository, perhaps it has to do with the chosen language (python instead of java). For me it is not annoying, so we can ignore it.

**Pull request merged**
